# Load balance requests between two limitr instances running on port 8000
# !!! ENSURE these instances match docker-compose.yml service names and ports !!!!
upstream limitr {
    server limitr-1:8000;
    server limitr-2:8000;
}

server {
    listen 80;

    location / {
        proxy_pass http://limitr;                 # Pass requests to any of the limitr servers
        proxy_set_header Host $host;              # Original Host header
        proxy_set_header X-Real-IP $remote_addr;  # Client IP
    }
}
